index/urls.py
from django.urls import path
from index.views import *

app_name = 'index'

urlpatterns = [
    path('<int:page>', view=index, name='index_page'),
    path('', view=index, name='index')
]

othersite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

from othersite import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

index/models.py
from django.db import models


# Create your models here.
class Employee(models.Model):

    def __str__(self):
        return f"{self.surname} {self.name} {self.patronymic}"

    citizenship_choices = [
        ("ru", "Россия"),
        ("us", "Америка")
    ]

    name = models.CharField(max_length=50)
    surname = models.CharField(max_length=50)
    patronymic = models.CharField(max_length=50)
    age = models.PositiveSmallIntegerField()
    weight = models.PositiveSmallIntegerField()
    citizenship = models.CharField(max_length=50, choices=citizenship_choices)
    description = models.CharField(max_length=300)
    work_schedule = models.CharField(max_length=300)
    skills = models.CharField(max_length=1000)
    hobbies = models.CharField(max_length=1000)
    personal_qualities = models.CharField(max_length=1000)
    additional_training = models.CharField(max_length=1000)

index/views.py
from django.shortcuts import render
from django.forms.models import model_to_dict
from django.template.defaulttags import register

# Create your views here.
from index.models import Employee


@register.filter
def get_range(employees):
    if employees % 5 == 0:
        pages_count = employees // 5
    else:
        pages_count = (employees // 5) + 1
    return [i+1 for i in range(pages_count)]


def index(request, page=None):
    hop = 5
    if page and page > 1:
        fid, lid = hop*page-hop+1, hop*page
        employees = Employee.objects.all()[fid-1:lid]
    else:
        employees = Employee.objects.all()[0:hop]
    employees_count = Employee.objects.count()
    context = {'employees': [model_to_dict(i) for i in employees], 'emp_count': employees_count}
    return render(request=request, template_name='index.html', context=context)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<title>W3.CSS Template</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-black.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
html,body,h1,h2,h3,h4,h5,h6 {font-family: "Roboto", sans-serif;}
.w3-sidebar {
  z-index: 3;
  width: 250px;
  top: 43px;
  bottom: 0;
  height: inherit;
}
</style>
<body>

<!-- Navbar -->
<div class="w3-top">
  <div class="w3-bar w3-theme w3-top w3-left-align w3-large">
    <a class="w3-bar-item w3-button w3-right w3-hide-large w3-hover-white w3-large w3-theme-l1" href="javascript:void(0)" onclick="w3_open()"><i class="fa fa-bars"></i></a>
    <a href="#" class="w3-bar-item w3-button w3-theme-l1">Logo</a>
    <a href="#" class="w3-bar-item w3-button w3-hide-small w3-hover-white">About</a>
    <a href="#" class="w3-bar-item w3-button w3-hide-small w3-hover-white">Values</a>
    <a href="#" class="w3-bar-item w3-button w3-hide-small w3-hover-white">News</a>
    <a href="#" class="w3-bar-item w3-button w3-hide-small w3-hover-white">Contact</a>
    <a href="#" class="w3-bar-item w3-button w3-hide-small w3-hide-medium w3-hover-white">Clients</a>
    <a href="#" class="w3-bar-item w3-button w3-hide-small w3-hide-medium w3-hover-white">Partners</a>
  </div>
</div>

<!-- Sidebar -->
<nav class="w3-sidebar w3-bar-block w3-collapse w3-large w3-theme-l5 w3-animate-left" id="mySidebar">
  <a href="javascript:void(0)" onclick="w3_close()" class="w3-right w3-xlarge w3-padding-large w3-hover-black w3-hide-large" title="Close Menu">
    <i class="fa fa-remove"></i>
  </a>
  <h4 class="w3-bar-item"><b>Menu</b></h4>
  <a class="w3-bar-item w3-button w3-hover-black" href="#">Link</a>
  <a class="w3-bar-item w3-button w3-hover-black" href="#">Link</a>
  <a class="w3-bar-item w3-button w3-hover-black" href="#">Link</a>
  <a class="w3-bar-item w3-button w3-hover-black" href="#">Link</a>
</nav>

<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<!-- Main content: shift it to the right by 250 pixels when the sidebar is visible -->
<div class="w3-main" style="margin-left:250px">
{% block content %}
{% endblock %}

  <footer id="myFooter">
    <div class="w3-container w3-theme-l2 w3-padding-32">
      <h4>Footer</h4>
    </div>

    <div class="w3-container w3-theme-l1">
      <p>Powered by <a href="https://www.w3schools.com/w3css/default.asp" target="_blank">w3.css</a></p>
    </div>
  </footer>

<!-- END MAIN -->
</div>

<script>
// Get the Sidebar
var mySidebar = document.getElementById("mySidebar");

// Get the DIV with overlay effect
var overlayBg = document.getElementById("myOverlay");

// Toggle between showing and hiding the sidebar, and add overlay effect
function w3_open() {
  if (mySidebar.style.display === 'block') {
    mySidebar.style.display = 'none';
    overlayBg.style.display = "none";
  } else {
    mySidebar.style.display = 'block';
    overlayBg.style.display = "block";
  }
}

// Close the sidebar with the close button
function w3_close() {
  mySidebar.style.display = "none";
  overlayBg.style.display = "none";
}
</script>

</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block content %}
    {% for emp in employees %}
      <div class="w3-row w3-padding-64">
        <div class="w3-twothird w3-container">
          <h1 class="w3-text-teal">{{ emp.surname }} {{ emp.name }} {{ emp.patronymic }}</h1>
            <h5>Возраст: {{ emp.age }}</h5>
            <h5>Информация: {{ emp.description }}</h5>
            <h5>Навыки: {{ emp.skills }}</h5>

        </div>
        <div class="w3-third w3-container">
          <p class="w3-border w3-padding-large w3-padding-32 w3-center">AD</p>
          <p class="w3-border w3-padding-large w3-padding-64 w3-center">AD</p>
        </div>
      </div>
    {% endfor %}
    <!-- Pagination -->
      <div class="w3-center w3-padding-32">
        <div class="w3-bar">
            {% for i in emp_count|get_range %}
                <a class="w3-button w3-black" href="{% url 'index:index_page' i%}">{{ i }}</a>
            {% endfor %}
        </div>
      </div>
{% endblock %}